environment:
  FORCE_COLOR: 1
  matrix:
    - nodejs_version: "10"
    - nodejs_version: ""

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.npm'
  - '%USERPROFILE%\.cache'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn
  - yarn install --frozen-lockfile

build_script:
  - yarn build

test_script:
  - yarn test -i
