sudo: false
dist: trusty

language: node_js
node_js: 8

cache:
  yarn: true
  directories:
    - ./node_modules
    - ./test-app/node_modules

before_install:
  - npm i -g yarn
  - export NODE_PATH="$PWD/test-app/node_modules:$NODE_PATH" # will prevent ESLint to fails when requiring plugins

install:
  - yarn install --frozen-lockfile
  - (cd test-app; yarn install --frozen-lockfile)

script:
  - cd test-app

  - yarn lint:fix # will fix test-app/src/StoreLocatorBundle/Resources/private/js/yprox-store-locator/components/LocatorFilter.js:45
  - yarn lint

  - rm -fr public/{css,img,js,plugins}
  - yarn build:prod
  - ../ci/test_build_prod.sh

  - rm -fr public/{css,img,js,plugins}
  - yarn build:dev
  - ../ci/test_build_dev.sh
