dist: trusty

language: node_js
node_js:
  - "10"
  - "lts/*"
  - node

env:
  global:
    - FORCE_COLOR=1

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

notifications:
  email: false

cache:
  directories:
    - ~/.nvm
    - ./node_modules

before_install:
  - npm i -g yarn

install:
  - yarn install --frozen-lockfile

script:
  - set -e # stop if one of the following lines fails, see https://github.com/travis-ci/travis-ci/issues/1066
  - yarn build
  - yarn lint
  - yarn test -i
  - npm pack # display which files will be packaged and sent to npm
  - set +e # disable "fast fail"

jobs:
  include:
    - stage: Release
      if: branch = master
      node_js: node
      script:
        - yarn build
        - yarn semantic-release
