sudo: false
dist: trusty

language: node_js
node_js: 8

cache:
  yarn: true

before_install:
  - npm i -g yarn@^1.12
  - export NODE_PATH="$PWD/test-app/node_modules:$NODE_PATH" # will prevent ESLint to fails when requiring plugins

install:
  - yarn install --frozen-lockfile

script:
  # will fix test-app/src/StoreLocatorBundle/Resources/private/js/yprox-store-locator/components/LocatorFilter.js:45
  - yarn lint-test-app --filter:handler rollup --fix
  - yarn lint-test-app --filter:handler rollup

  # will fix test-app/themes/_containers/containers.scss
  - yarn lint-test-app --filter:handler sass --fix
  - yarn lint-test-app --filter:handler sass

  - rm -fr public/{css,img,js,plugins}
  - yarn build-test-app:prod
  - ../ci/test_build_prod.sh

  - rm -fr public/{css,img,js,plugins}
  - yarn build-test-app:dev
  - ../ci/test_build_dev.sh

  - rm -fr public/css
  - yarn build-test-app:dev --filter:handler sass --filter:handler css
  - ../ci/test_build_dev.sh
