name: CI

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

env:
    CI: true

jobs:
    ci:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest]
                nodejs: [10.x, 12.x, 13.x]
        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v4

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v4
                with:
                    node-version: ${{ matrix.node-version }}
                    registry-url: 'https://npm.pkg.github.com'
                    scope: '@yproximite'
                    always-auth: true

            -   name: Get yarn cache directory
                id: yarn-cache
                run: echo "::set-output name=dir::$(yarn cache dir)"

            -   name: Restore yarn cache (if available)
                uses: actions/cache@v4
                with:
                    path: ${{ steps.yarn-cache.outputs.dir }}
                    key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-yarn-

            -   run: yarn install --frozen-lockfile
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   run: yarn build

            -   run: yarn lint

            -   run: yarn test -i

            -   run: npm pack
