name: Release

on:
    push:
        branches:
            - master

env:
    CI: true
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Install Node.js
                uses: actions/setup-node@v1
                with:
                    node-version: 10.x

            -   run: yarn install --frozen-lockfile

            -   run: yarn build

            -   run: yarn semantic-release
