name: Release

on:
    push:
        branches:
            - master

env:
    CI: true

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Install Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: ${{ matrix.node-version }}
                    registry-url: 'https://npm.pkg.github.com'
                    scope: '@yproximite'
                    always-auth: true

            -   run: yarn install --frozen-lockfile
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   run: yarn build

            -   run: yarn semantic-release
                env:
                    NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
